#guess a random number generated by the function "random"
#random.randint(a, b)
#Retorna un entero aleatorio N tal que a <= N <= b. Alias de randrange(a, b+1).
import random

def guess(x):
    random_number = random.randint(1,x)
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_number:
            print("Sorry, guess again, too low.!")
        elif guess > random_number:
            print("sorry, guess again. too high.!")
    print(f"Yeah. Congrats!! You guessed the number: {random_number} correctly")

guess(10)